version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development
      DB_HOSTNAME: postgres_db
      DB_USER: postgres
      DB_PASS: 12345
      DB_NAME: test_db
      APP_SETTINGS: DevelopmentConfig
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
