x-common-env-vars: &common-env-vars
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 12345
    POSTGRES_DB: test_db
    DB_HOSTNAME: db

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      <<: *common-env-vars
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0
    environment:
      <<: *common-env-vars
      FLASK_ENV: development
      APP_SETTINGS: DevelopmentConfig
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
